from collections import deque

stack = deque()
# print(dir(stack))
stack.append(12)
stack.append("Shukla")
stack.append(24)
stack.append("Priyansh")
stack.append(36)
# print(stack)
# stack.clear()
# print(stack)
# stack1 = stack.copy()
# print(stack.count(12))
print(stack.index(12))
stack.insert(0, 1)
stack.insert(0, 2)
stack.insert(0, 5)
stack.insert(0, 15)
# print(stack)
stack.remove(15)
# print(stack)
stack.reverse()
# print(stack)

stack.pop()
print(stack)
stack.pop()
print(stack)
